<?php
declare(strict_types=1);
$legalPage=['title'=>'Terms of Service','eyebrow'=>'Account and service terms','summary'=>'The rules for accessing Valtoria, requesting financial operations, understanding manual review, and keeping your account secure.','notice_title'=>'Requests are not instant transactions','notice'=>'Funding, transfer, and credit submissions may require manual review. A request is not complete until its status is marked completed and the corresponding account entry is posted.','sections'=>[
['number'=>'01','id'=>'agreement','title'=>'Agreement and service operator','content'=>'<p>These Terms govern your use of Valtoria and form part of your agreement with the operator identified in your account-specific agreement or product disclosure. By using an account, you agree to these Terms, the Privacy Policy, applicable product terms, fee disclosures, and pre-submission instructions.</p><p>More specific product terms control if they conflict with these general Terms. Availability, eligibility, limits, and legal protections vary by jurisdiction.</p>'],
['number'=>'02','id'=>'eligibility','title'=>'Eligibility and account information','content'=>'<p>You must have legal capacity, meet disclosed age and location requirements, and provide accurate information. Use only your own account unless formally authorized for another person or organization.</p><p>We may request verification before opening an account, enabling a feature, or processing an operation. Platform access does not guarantee approval of funding, transfer, or credit.</p>'],
['number'=>'03','id'=>'security','title'=>'Your security responsibilities','content'=>'<ul><li>Protect your password, one-time codes, devices, and recovery details.</li><li>Review beneficiaries, amounts, fees, and instructions before submitting.</li><li>Promptly report unauthorized access, incorrect data, or unrecognized activity.</li><li>Never place a full card number or security code in messages, email, notes, or support tickets.</li></ul>'],
['number'=>'04','id'=>'operations','title'=>'How operation requests work','content'=>'<p>Funding, card-to-card transfer, credit, and repayment requests may be checked manually. We may approve, decline, pause, request information, or cancel for legal, risk, security, eligibility, balance, limit, operational, or partner reasons.</p><div class="legal-table-wrap"><table class="legal-table"><thead><tr><th>Status</th><th>Meaning</th></tr></thead><tbody><tr><td>Pending</td><td>Received and awaiting review.</td></tr><tr><td>Processing</td><td>Approved for operational handling but not final.</td></tr><tr><td>Completed</td><td>Finalized in Valtoria’s record and posted to the applicable ledger.</td></tr><tr><td>Failed</td><td>Not completed; correction or a new request may be needed.</td></tr><tr><td>Reversed</td><td>A correcting entry was posted against a completed operation.</td></tr></tbody></table></div><p>Use the authenticated record and available balance—not email, screenshots, or verbal statements—as the service record.</p>'],
['number'=>'05','id'=>'cards','title'=>'Partner cards and funding','content'=>'<p>Only compatible cards supported through an approved partner arrangement may be eligible. A network name or logo does not imply endorsement. The cardholder must authorize use.</p><p>Required card details may be provided only through a designated secure process, never email or general support. Security codes must not be retained after authorization. Permitted masked metadata and references may be kept for display, reconciliation, disputes, and compliance.</p>'],
['number'=>'06','id'=>'balances','title'=>'Balances, limits, fees, and corrections','content'=>'<p>Applicable amounts, fees, limits, and totals are shown before confirmation or in product disclosures. Pending or processing items may not affect available balance until posted. We may correct duplicate, erroneous, unauthorized, or reversed entries through traceable accounting records rather than silently rewriting completed records.</p>'],
['number'=>'07','id'=>'credit','title'=>'Credit requests','content'=>'<p>A credit application is a request, not a promise to lend. Eligibility, pricing, terms, documents, disbursement, repayment, and notices are governed by the credit agreement and applicable law. Credit is not available until approved, agreed, and recorded as disbursed.</p>'],
['number'=>'08','id'=>'prohibited','title'=>'Prohibited use','content'=>'<p>Do not use the service for fraud, money laundering, sanctions evasion, unlawful commerce, unauthorized access, impersonation, abusive automation, security interference, or a card or account you are not authorized to use.</p>'],
['number'=>'09','id'=>'restriction','title'=>'Suspension, closure, and availability','content'=>'<p>We may restrict features, hold requests, suspend access, or close accounts where reasonably necessary for security, investigation, law, partner requirements, service integrity, or breach. Where permitted, we will explain the action and provide a support route. Services may be interrupted and no requested product is guaranteed to remain available.</p>'],
['number'=>'10','id'=>'liability','title'=>'Liability, complaints, and changes','content'=>'<p>Nothing excludes rights or liability that cannot lawfully be excluded. Applicable warranty limits, liability caps, governing law, complaint route, regulator or ombudsman, and dispute forum are stated in your account-specific agreement.</p><p>We may update these Terms for legal, security, operational, or product reasons and will provide notice where required.</p>']]];
require __DIR__.'/includes/legal_page.php';
