<?php
declare(strict_types=1);
$adminPage='approvals';$adminTitle='Account approvals';$adminPermission='customers.manage';require __DIR__.'/../includes/admin_header.php';
$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{requireCsrf();$userId=(int)($_POST['user_id']??0);$decision=(string)($_POST['decision']??'');if(!in_array($decision,['approved','rejected'],true))throw new InvalidArgumentException('Invalid approval decision.');$pdo->beginTransaction();$stmt=$pdo->prepare("SELECT user_id,status FROM users WHERE user_id=? AND role='customer' FOR UPDATE");$stmt->execute([$userId]);$customer=$stmt->fetch();if(!$customer||$customer['status']!=='pending')throw new RuntimeException('This application is no longer awaiting review.');$pdo->prepare('UPDATE users SET status=?,is_active=?,session_version=session_version+1 WHERE user_id=?')->execute([$decision,$decision==='approved'?1:0,$userId]);if($decision==='approved'){$account=$pdo->prepare('SELECT 1 FROM accounts WHERE user_id=?');$account->execute([$userId]);if(!$account->fetchColumn())$pdo->prepare('INSERT INTO accounts(user_id,account_number,balance_cents) VALUES(?,?,0)')->execute([$userId,generateUniqueAccountNumber($pdo)]);}audit($pdo,'customer.application_'.$decision,'user',$userId,['reason'=>mb_substr(trim((string)($_POST['reason']??'')),0,500)]);$pdo->commit();$notice='Application '.$decision.'.';}catch(Throwable $exception){if($pdo->inTransaction())$pdo->rollBack();$error=$exception->getMessage();}}
$pending=$pdo->query("SELECT u.user_id,u.full_name,u.email,u.phone,u.created_at,a.account_number FROM users u LEFT JOIN accounts a ON a.user_id=u.user_id WHERE u.role='customer' AND u.status='pending' ORDER BY u.created_at")->fetchAll();
?>
<?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif?><?php if($error):?><div class="notice error" role="alert"><?=e($error)?></div><?php endif?>
<section class="panel"><div class="admin-section-head"><div><h2>Pending applications</h2><p class="muted">This queue is used only while “Require account approval” is enabled.</p></div><span class="badge pending"><?=count($pending)?> pending</span></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Submitted</th><th>Customer</th><th>Contact</th><th>Account</th><th>Decision</th></tr></thead><tbody><?php foreach($pending as $customer):?><tr><td><?=e(formatDate($customer['created_at']))?></td><td><strong><?=e($customer['full_name'])?></strong></td><td><?=e($customer['email'])?><br><small><?=e($customer['phone'])?></small></td><td class="mono"><?=e($customer['account_number']??'Created on approval')?></td><td><form method="post" class="compact-form"><?=csrfField()?><input type="hidden" name="user_id" value="<?=(int)$customer['user_id']?>"><input name="reason" maxlength="500" placeholder="Review note"><button class="button button-primary" name="decision" value="approved">Approve</button><button class="button button-danger" name="decision" value="rejected">Reject</button></form></td></tr><?php endforeach?><?php if(!$pending):?><tr><td colspan="5"><div class="empty">No applications are awaiting review.</div></td></tr><?php endif?></tbody></table></div></section>
<?php require __DIR__.'/../includes/admin_footer.php';?>
