<?php
declare(strict_types=1);
$adminPage='credit';$adminTitle='Credit operations';$adminPermission='credit.view';require __DIR__.'/../includes/admin_header.php';
$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{requireCsrf();requirePermission('credit.manage');$id=(int)($_POST['application_id']??0);$decision=(string)($_POST['decision']??'');$approved=$decision==='approved'?Money::fromDecimal((string)($_POST['approved_amount']??'')):null;$note=trim((string)($_POST['note']??''));if(mb_strlen($note)<3)throw new InvalidArgumentException('Record a concise underwriting note.');(new CreditService($pdo))->decide($id,(int)$_SESSION['user_id'],$decision,$approved,$note);$notice='Credit decision recorded.';}catch(Throwable $exception){$error=$exception->getMessage();}}
$status=(string)($_GET['status']??'');$allowed=['under_review','approved','rejected','needs_information','accepted'];$params=[];$where='1=1';if(in_array($status,$allowed,true)){$where='ca.status=?';$params[]=$status;}$stmt=$pdo->prepare("SELECT ca.*,u.full_name,u.email,rv.full_name reviewer FROM credit_applications ca JOIN users u ON u.user_id=ca.user_id LEFT JOIN users rv ON rv.user_id=ca.reviewed_by WHERE $where ORDER BY FIELD(ca.status,'under_review','needs_information','approved','accepted','rejected'),ca.created_at DESC LIMIT 150");$stmt->execute($params);$applications=$stmt->fetchAll();$facilities=$pdo->query("SELECT cf.reference,cf.status,cf.principal_cents,cf.outstanding_cents,u.full_name,u.email,(SELECT MIN(due_date) FROM repayment_schedule rs WHERE rs.facility_id=cf.facility_id AND rs.status<>'paid') next_due FROM credit_facilities cf JOIN users u ON u.user_id=cf.user_id ORDER BY cf.created_at DESC LIMIT 100")->fetchAll();
?>
<?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?>
<section class="panel"><div class="admin-section-head"><div><h2>Application queue</h2><p class="muted">Visa eligibility is checked before submission; decisions are manual and audited.</p></div><form method="get" class="compact-form"><label for="status">Status</label><select id="status" name="status"><option value="">All</option><?php foreach($allowed as $value):?><option value="<?=e($value)?>" <?=$status===$value?'selected':''?>><?=e(str_replace('_',' ',$value))?></option><?php endforeach?></select><button class="button button-secondary">Filter</button></form></div>
<div class="table-wrap"><table class="data-table"><thead><tr><th>Customer</th><th>Requested</th><th>Term</th><th>Status</th><th>Decision</th></tr></thead><tbody><?php foreach($applications as $application):?><tr><td><strong><?=e($application['full_name'])?></strong><br><small><?=e($application['email'])?></small></td><td class="money"><?=Money::format((int)$application['requested_amount_cents'])?></td><td><?=(int)$application['term_months']?> months</td><td><span class="badge <?=e($application['status'])?>"><?=e(str_replace('_',' ',$application['status']))?></span></td><td><?php if($application['status']==='under_review'&&can('credit.manage')):?><form method="post" class="compact-form"><?=csrfField()?><input type="hidden" name="application_id" value="<?=(int)$application['application_id']?>"><select name="decision" aria-label="Decision"><option value="needs_information">Needs information</option><option value="approved">Approve</option><option value="rejected">Reject</option></select><input name="approved_amount" inputmode="decimal" placeholder="Approved USD"><input name="note" maxlength="1000" required placeholder="Underwriting note"><button class="button button-secondary">Record</button></form><?php else:?><?=e($application['reviewer']??'—')?><?php endif?></td></tr><?php endforeach?><?php if(!$applications):?><tr><td colspan="5"><div class="empty">No applications match this filter.</div></td></tr><?php endif?></tbody></table></div></section>
<section class="panel" style="margin-top:20px"><h2>Credit facilities</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Customer</th><th>Principal</th><th>Outstanding</th><th>Next due</th><th>Status</th></tr></thead><tbody><?php foreach($facilities as $facility):?><tr><td class="mono"><?=e($facility['reference'])?></td><td><?=e($facility['full_name'])?><br><small><?=e($facility['email'])?></small></td><td class="money"><?=Money::format((int)$facility['principal_cents'])?></td><td class="money"><?=Money::format((int)$facility['outstanding_cents'])?></td><td><?=e($facility['next_due']??'—')?></td><td><span class="badge <?=e($facility['status'])?>"><?=e($facility['status'])?></span></td></tr><?php endforeach?></tbody></table></div></section>
<?php require __DIR__.'/../includes/admin_footer.php';?>
