<?php
declare(strict_types=1);
$adminPage='settings';$adminTitle='Products & access';$adminPermission='settings.manage';require __DIR__.'/../includes/admin_header.php';
$notice='';$error='';
$definitions=[
 'features.require_account_approval'=>['Require account approval','Hold new accounts for an administrator before sign-in. When disabled, accounts are approved and signed in immediately.'],
 'features.email_otp'=>['Email OTP at sign-in','Require a six-digit email code after password verification. Keep disabled until SMTP is configured and tested.'],
 'features.card_funding'=>['Card funding','Allow customers to submit funding requests for manual operations review.'],
 'features.transfers'=>['Transfers','Allow customers to initiate card-to-card transfers.'],
 'features.credit_applications'=>['Credit applications','Allow eligible Visa cardholders to submit credit applications.'],
 'features.support_cases'=>['Support cases','Allow customers to create and reply to authenticated support cases.'],
 'system.maintenance_mode'=>['Maintenance mode','Temporarily block customer application access while preserving operations access.'],
];
if($_SERVER['REQUEST_METHOD']==='POST'){try{requireCsrf();$action=$_POST['action']??'';if($action==='setting'){$key=(string)($_POST['key']??'');if(!isset($definitions[$key]))throw new InvalidArgumentException('Setting is not editable.');$value=($_POST['enabled']??'0')==='1';if($key==='features.email_otp'&&$value){$mail=config('mail');foreach(['host','username','password','from_address'] as $field){if(empty($mail[$field]))throw new RuntimeException('Configure and enable SMTP before enabling email OTP.');}if(empty($mail['enabled']))throw new RuntimeException('Set MAIL_ENABLED=true before enabling email OTP.');}$stmt=$pdo->prepare('INSERT INTO product_settings(setting_key,value_json,updated_by) VALUES(?,?,?) ON DUPLICATE KEY UPDATE value_json=VALUES(value_json),updated_by=VALUES(updated_by)');$stmt->execute([$key,$value?'true':'false',$_SESSION['user_id']]);audit($pdo,'product_setting.changed','product_setting',$key,['enabled'=>$value]);$notice='Feature setting updated.';}elseif($action==='role'){requirePermission('roles.manage');$userId=(int)($_POST['user_id']??0);$role=(string)($_POST['role']??'');$roles=['super_admin','operations','kyc_reviewer','credit_officer','support_agent','read_only_auditor'];if(!in_array($role,$roles,true)||$userId===(int)$_SESSION['user_id'])throw new InvalidArgumentException('Invalid or self-directed role change.');$stmt=$pdo->prepare('UPDATE users SET role=?,is_admin=1,session_version=session_version+1 WHERE user_id=? AND is_admin=1');$stmt->execute([$role,$userId]);if(!$stmt->rowCount())throw new RuntimeException('Administrator was not found.');audit($pdo,'admin.role_changed','user',$userId,['role'=>$role]);$notice='Role updated and existing sessions invalidated.';}else throw new InvalidArgumentException('Unsupported settings action.');}catch(Throwable $exception){$error=$exception->getMessage();}}
$settings=$pdo->query("SELECT * FROM product_settings WHERE setting_key LIKE 'features.%' OR setting_key='system.maintenance_mode' ORDER BY setting_key")->fetchAll();$byKey=[];foreach($settings as $row)$byKey[$row['setting_key']]=$row;$admins=$pdo->query("SELECT user_id,full_name,email,role,is_active FROM users WHERE is_admin=1 ORDER BY full_name")->fetchAll();$mail=config('mail');$mailReady=(bool)$mail['enabled']&&!empty($mail['host'])&&!empty($mail['username'])&&!empty($mail['password'])&&!empty($mail['from_address']);
?>
<?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif?><?php if($error):?><div class="notice error" role="alert"><?=e($error)?></div><?php endif?>
<div class="app-grid"><section class="panel span-7"><h2>Onboarding and product controls</h2><p class="muted">Switches are enforced by the server. Changes are recorded in the audit log.</p>
<?php foreach($definitions as $key=>$definition):$row=$byKey[$key]??null;$enabled=$row&&json_decode($row['value_json'],true)===true;?><form method="post" class="admin-section-head note"><?=csrfField()?><input type="hidden" name="action" value="setting"><input type="hidden" name="key" value="<?=e($key)?>"><div><strong><?=e($definition[0])?></strong><p class="muted" style="margin:.25rem 0"><?=e($definition[1])?></p><span class="badge <?=$enabled?'active':'disabled'?>"><?=$enabled?'enabled':'disabled'?></span><?php if($key==='features.email_otp'):?> <span class="badge <?=$mailReady?'active':'failed'?>">SMTP <?=$mailReady?'ready':'not configured'?></span><?php endif?></div><input type="hidden" name="enabled" value="<?=$enabled?'0':'1'?>"><button class="button button-secondary" <?=($key==='features.email_otp'&&!$enabled&&!$mailReady)?'disabled title="Configure SMTP first"':''?>><?=$enabled?'Disable':'Enable'?></button></form><?php endforeach?></section>
<section class="panel span-5"><h2>Roles and permissions</h2><p class="muted">Role changes invalidate existing sessions. Self-role changes are blocked.</p><?php foreach($admins as $admin):?><form method="post" class="note compact-form"><?=csrfField()?><input type="hidden" name="action" value="role"><input type="hidden" name="user_id" value="<?=(int)$admin['user_id']?>"><span><strong><?=e($admin['full_name'])?></strong><br><small><?=e($admin['email'])?></small></span><select name="role" <?=$admin['user_id']===$_SESSION['user_id']?'disabled':''?>><?php foreach(['super_admin','operations','kyc_reviewer','credit_officer','support_agent','read_only_auditor'] as $role):?><option value="<?=e($role)?>" <?=$admin['role']===$role?'selected':''?>><?=e(str_replace('_',' ',$role))?></option><?php endforeach?></select><button class="button button-secondary" <?=$admin['user_id']===$_SESSION['user_id']?'disabled':''?>>Save</button></form><?php endforeach?></section></div>
<?php require __DIR__.'/../includes/admin_footer.php';?>
