<?php
$adminPage='transactions';$adminTitle='Money movement';$adminPermission='transactions.view';require __DIR__.'/../includes/admin_header.php';$notice='';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){try{requireCsrf();requirePermission('transactions.reverse');$action=$_POST['action']??'';$reference=trim($_POST['reference']??'');$reason=trim($_POST['reason']??'');if($action==='reverse'){$result=(new FinancialService($pdo))->reverse($reference,(int)$_SESSION['user_id'],$reason);$notice='Correcting transaction '.$result['reference'].' was posted.';}elseif($action==='review'){$result=(new FinancialService($pdo))->review($reference,(string)($_POST['next_status']??''),(int)$_SESSION['user_id'],$reason);$notice=$result['reference'].' is now '.$result['status'].'.';}else throw new InvalidArgumentException('Invalid operations action.');}catch(Throwable $e){$error=$e->getMessage();}}
$type=$_GET['type']??'';$status=$_GET['status']??'';$q=trim($_GET['q']??'');$params=[];$where=['1=1'];if($type!==''){$where[]='ft.type=?';$params[]=$type;}if($status!==''){$where[]='ft.status=?';$params[]=$status;}if($q!==''){$where[]='(ft.reference LIKE ? OR u.email LIKE ?)';$params[]='%'.$q.'%';$params[]='%'.$q.'%';}$stmt=$pdo->prepare('SELECT ft.*,u.full_name,u.email,a.account_number FROM financial_transactions ft JOIN users u ON u.user_id=ft.user_id JOIN accounts a ON a.account_id=ft.account_id WHERE '.implode(' AND ',$where).' ORDER BY FIELD(ft.status,\'pending\',\'processing\',\'failed\',\'completed\',\'reversed\'),ft.created_at DESC LIMIT 200');$stmt->execute($params);$rows=$stmt->fetchAll();
?><style>.review-form{display:grid;grid-template-columns:minmax(145px,.7fr) minmax(210px,1.4fr) auto;gap:8px;align-items:center}.review-form input,.review-form select{min-height:40px;padding:8px 10px;border:1px solid #d0d5dd;border-radius:9px;background:#fff}@media(max-width:680px){.review-form{grid-template-columns:1fr}}</style>
<?php if($notice):?><div class="notice success"><?=e($notice)?></div><?php endif?><?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?>
<div class="notice"><strong>Two-stage review:</strong> move a pending request to processing after initial checks, then complete it only after partner handling is confirmed. Ledger entries and balances post only on completion.</div>
<form class="toolbar" method="get"><div class="field"><label>Reference or email</label><input name="q" value="<?=e($q)?>"></div><div class="field"><label>Type</label><select name="type"><option value="">All types</option><?php foreach(['card_funding','card_transfer','credit_disbursement','credit_repayment','reversal'] as $v):?><option value="<?=$v?>" <?=$type===$v?'selected':''?>><?=e(str_replace('_',' ',$v))?></option><?php endforeach?></select></div><div class="field"><label>Status</label><select name="status"><option value="">All statuses</option><?php foreach(['pending','processing','completed','failed','reversed'] as $v):?><option value="<?=$v?>" <?=$status===$v?'selected':''?>><?=$v?></option><?php endforeach?></select></div><button class="button button-primary">Filter</button></form>
<section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Reference/time</th><th>Customer</th><th>Type</th><th>Amount/fee</th><th>Partner ref.</th><th>Status</th><th>Operations action</th></tr></thead><tbody><?php foreach($rows as $row):?><tr><td class="mono"><?=e($row['reference'])?><br><small><?=e(formatDate($row['created_at']))?></small></td><td><?=e($row['full_name'])?><br><small><?=e($row['account_number'])?></small></td><td><?=e(str_replace('_',' ',$row['type']))?></td><td class="money"><?=Money::format((int)$row['amount_cents'])?><br><small>Fee <?=Money::format((int)$row['fee_cents'])?></small></td><td class="mono"><?=e($row['provider_reference']??'—')?></td><td><span class="badge <?=e($row['status'])?>"><?=e($row['status'])?></span></td><td>
<?php if(can('transactions.reverse')&&in_array($row['type'],['card_funding','card_transfer'],true)&&in_array($row['status'],['pending','processing'],true)):?><form method="post" class="review-form"><?=csrfField()?><input type="hidden" name="action" value="review"><input type="hidden" name="reference" value="<?=e($row['reference'])?>"><select name="next_status" required><?php if($row['status']==='pending'):?><option value="processing">Mark processing</option><?php else:?><option value="completed">Mark completed</option><?php endif?><option value="failed">Mark failed</option></select><input name="reason" minlength="5" maxlength="500" required placeholder="Review note / partner confirmation"><button class="button button-secondary">Apply</button></form>
<?php elseif(can('transactions.reverse')&&$row['status']==='completed'&&$row['type']!=='reversal'):?><form method="post" class="compact-form"><?=csrfField()?><input type="hidden" name="action" value="reverse"><input type="hidden" name="reference" value="<?=e($row['reference'])?>"><input name="reason" minlength="8" maxlength="220" required placeholder="Correction reason"><button class="button button-danger">Reverse</button></form><?php else:?>—<?php endif?></td></tr><?php endforeach?></tbody></table></div><?php if(!$rows):?><div class="empty">No transactions match these filters.</div><?php endif?></section><?php require __DIR__.'/../includes/admin_footer.php';?>
