<?php
require_once __DIR__ . '/../app/bootstrap_financial.php';redirectIfNotLoggedIn();enforceSessionVersion($pdo);
if(!isAdmin()&&featureEnabled($pdo,'system.maintenance_mode',false)){http_response_code(503);header('Retry-After: 300');exit('Valtoria account services are temporarily unavailable for scheduled maintenance.');}
$appPage=$appPage??'';$appTitle=$appTitle??'Valtoria Bank';$customerId=(int)$_SESSION['user_id'];
$customerCssVersion=(string)filemtime(VALTORIA_ROOT.'/assets/css/customer-app.css');$customerJsVersion=(string)filemtime(VALTORIA_ROOT.'/assets/js/customer-app.js');
$customerNav=[['dashboard','dashboard','Overview'],['cards','card-center','Cards'],['funding','funding','Card funding'],['transfer','transfer','Transfers'],['beneficiaries','beneficiaries','Beneficiaries'],['transactions','transactions','Transactions'],['credit','credit-center','Credit'],['notifications','notifications','Notifications'],['support','support','Support'],['profile','profile','Profile & security']];
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=e($appTitle)?> | Valtoria Bank</title><link rel="icon" href="../assets/images/brand/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="../assets/css/customer-app.css?v=<?=e($customerCssVersion)?>"><script src="../assets/js/customer-app.js?v=<?=e($customerJsVersion)?>" defer></script></head><body><a class="skip-link" href="#customer-main">Skip to account content</a><div class="app-shell">
<aside class="app-sidebar" id="customer-menu"><div class="sidebar-brand"><a class="valtoria-wordmark" href="dashboard">Valtoria</a><button class="menu-close" type="button" data-menu-close aria-label="Close navigation">×</button></div><nav class="app-nav" aria-label="Customer navigation"><?php foreach($customerNav as $item):?><a class="<?=$appPage===$item[0]?'active':''?>" href="<?=e($item[1])?>"><span class="nav-mark" aria-hidden="true"><?=e(strtoupper(substr($item[2],0,1)))?></span><?=e($item[2])?></a><?php endforeach?></nav><div class="sidebar-foot"><span>Signed in securely</span><a href="../logout">Sign out</a></div></aside>
<button class="menu-scrim" type="button" data-menu-close tabindex="-1" aria-label="Close navigation"></button><div class="app-main"><header class="app-topbar"><div class="topbar-heading"><button class="menu-toggle" type="button" aria-controls="customer-menu" aria-expanded="false" aria-label="Open navigation"><span></span><span></span><span></span></button><div><span class="page-kicker">Customer workspace</span><h1 class="app-title"><?=e($appTitle)?></h1></div></div><div class="topbar-actions"><a class="muted-link" href="../">Public site</a><a class="topbar-signout" href="../logout">Sign out</a></div></header><main class="app-content" id="customer-main">
