<?php
declare(strict_types=1);
$pages=[
'accounts'=>['eyebrow'=>'Personal banking','heading'=>'One clear place for your financial life.','intro'=>'Track available balance, requests, completed activity, statements, and support conversations from a focused customer workspace.','proof'=>['Authoritative ledger records','Searchable activity','Mobile-ready workspace'],'steps'=>[['Open and verify','Create your account and complete any requested profile or eligibility checks.'],['Request an operation','Review the amount, fee, recipient, and terms before submitting.'],['Track the outcome','Follow pending, processing, completed, or failed status from your account.']],'detail'=>['Built for clarity','Balances change only when an operation is completed and posted. Receipts, references, timestamps, and status labels provide a consistent record.'],'faq'=>[['Is a pending item part of my balance?','Not necessarily. Pending and processing requests are not final and may not affect available balance until completion.'],['Can completed records be edited?','Corrections use traceable reversal entries rather than silently rewriting financial history.']]],
'cards'=>['eyebrow'=>'Card center','heading'=>'Partner cards, reviewed before use.','intro'=>'Submit masked metadata for a compatible partner card and track its compatibility review without exposing complete card details in the application.','proof'=>['Manual compatibility review','Masked card display','Visa and Mastercard support'],'steps'=>[['Submit metadata','Provide the network, name, expiry, last four digits, and an approved partner reference.'],['Operations reviews','Authorized staff confirm whether the card is compatible with the partner program.'],['Use after approval','Only verified, active cards become available for eligible funding requests.']],'detail'=>['Sensitive information stays out','Never place a full card number or security code in support messages, notes, email, or ordinary forms. Network support does not imply network endorsement.'],'faq'=>[['Why is my card pending?','A submitted card remains pending until operations confirms compatibility.'],['Can support ask for my security code?','No. Never send a card security code through support or email.']]],
'transfers'=>['eyebrow'=>'Transfers','heading'=>'Send with review, visibility, and control.','intro'=>'Create a beneficiary, preview the total, submit your request, and follow each manual operations stage through completion.','proof'=>['Amount and fee preview','Manual operations review','Traceable status history'],'steps'=>[['Choose a beneficiary','Select a saved destination and confirm the account details.'],['Review and submit','Check the recipient amount, fee, total debit, and memo.'],['Operations completes','The ledger moves funds only after the request passes review and is marked completed.']],'detail'=>['A request is not completion','Pending means received. Processing means operational handling is underway. Completed means the corresponding ledger entries were posted. Failed requests do not move funds.'],'faq'=>[['When is my balance debited?','At completion, after operations confirms the request and sufficient balance remains available.'],['Can a request fail after submission?','Yes. Eligibility, available balance, limits, security, or operational checks can prevent completion.']]],
'funding'=>['eyebrow'=>'Card funding','heading'=>'Request funding from an approved partner card.','intro'=>'Choose a verified card, review the funding amount and fee, then submit the request for manual partner handling.','proof'=>['Verified cards only','Transparent total','Ledger posting on completion'],'steps'=>[['Choose a card','Only cards approved through compatibility review are selectable.'],['Confirm the request','Review the requested credit, funding fee, and total partner charge.'],['Track manual review','Operations moves the request from pending to processing, then completed or failed.']],'detail'=>['No automatic card charge','The platform does not claim an external authorization. Authorized staff reconcile the partner operation and post the account credit only when completion is confirmed.'],'faq'=>[['Does submission credit my balance?','No. Your balance changes only after the request is completed.'],['Where should card details be sent?','Only through a separately approved secure partner channel—not support, email, or free-text forms.']]],
'credit'=>['eyebrow'=>'Credit','heading'=>'Credit decisions with explainable terms.','intro'=>'Eligible customers can submit a request, follow manual underwriting, review approved terms, and track repayment activity.','proof'=>['No guaranteed approval','Manual underwriting','Stored terms match schedules'],'steps'=>[['Check eligibility','Availability depends on configured account, card, activity, and product criteria.'],['Apply for review','Provide the amount, term, and purpose requested by the application.'],['Review the decision','Approval, requested information, rejection, acceptance, and disbursement remain distinct stages.']],'detail'=>['Approval is not disbursement','Funds become available only after approval, acceptance of applicable terms, and completion of the disbursement entry. Rates and schedules must match the agreement shown to you.'],'faq'=>[['Does eligibility guarantee approval?','No. Eligibility allows an application; underwriting determines the decision.'],['When does repayment begin?','The approved agreement and schedule define the due dates after disbursement.']]],
'security'=>['eyebrow'=>'Security','heading'=>'Security that matches the real operation.','intro'=>'Account controls, role-scoped administration, audit records, manual review, and careful handling of payment-card metadata work together.','proof'=>['Hashed passwords','Role-scoped access','Audited operations'],'steps'=>[['Protect access','Use a unique password and secure your email account and devices.'],['Review every request','Confirm destination, amount, fee, and current status in the authenticated workspace.'],['Report concerns','Change compromised credentials and contact secure support promptly.']],'detail'=>['Manual does not mean informal','Administrators must follow status transitions, record review notes, and post financial entries only when an operation is confirmed. Full card details and security codes do not belong in application records.'],'faq'=>[['Will support request my password or OTP?','No. Never disclose passwords or one-time codes.'],['What if I see unfamiliar activity?','Secure your account and open an authenticated support case immediately.']]],
'help'=>['eyebrow'=>'Help center','heading'=>'Clear answers, with a traceable support route.','intro'=>'Understand common account and operation states, resolve access issues, and contact the appropriate support channel.','proof'=>['Account-specific secure support','Operation references','Security-first guidance'],'steps'=>[['Check the status','Review the authenticated record, reference, timeline, and notifications.'],['Gather safe details','Share the operation reference and problem description—never passwords or complete card details.'],['Open a case','Signed-in customers can create a traceable support conversation.']],'detail'=>['Choose the safest channel','Use secure support for account-specific questions. General contact is for non-sensitive product enquiries and should never contain credentials or card data.'],'faq'=>[['What does processing mean?','The request passed initial review and is being handled, but it is not final.'],['How do I report a failed operation?','Open secure support and include its reference, status, and what you expected.']]],
];
$page=$pages[$productPage]??null;if(!$page){http_response_code(404);exit('Page not found');}$pageTitle=$page['heading'].' | Valtoria Bank';require __DIR__.'/public_header.php';
?>
<link rel="stylesheet" href="assets/css/product-pages.css"><link rel="stylesheet" href="assets/css/product-mobile.css">
<section class="product-hero"><div class="container product-hero-grid"><div><div class="eyebrow"><?=e($page['eyebrow'])?></div><h1><?=e($page['heading'])?></h1><p class="hero-copy"><?=e($page['intro'])?></p><div class="hero-actions"><a class="button button-primary" href="register.php">Open an account</a><a class="button button-secondary" href="login.php">Sign in</a></div></div><aside class="product-proof"><?php foreach($page['proof'] as $i=>$proof):?><div><span>0<?=$i+1?></span><strong><?=e($proof)?></strong></div><?php endforeach?></aside></div></section>
<section class="section"><div class="container"><div class="section-heading"><div class="eyebrow">How it works</div><h2>A deliberate path from request to record.</h2></div><div class="product-steps"><?php foreach($page['steps'] as $i=>$step):?><article><span>0<?=$i+1?></span><h3><?=e($step[0])?></h3><p><?=e($step[1])?></p></article><?php endforeach?></div></div></section>
<section class="section product-detail"><div class="container split-feature"><div><div class="eyebrow">Designed around trust</div><h2><?=e($page['detail'][0])?></h2><p class="hero-copy"><?=e($page['detail'][1])?></p></div><div class="status-card"><span class="mini-label">Operation lifecycle</span><ol><li><b>Pending</b><small>Received for review</small></li><li><b>Processing</b><small>Operational handling</small></li><li><b>Completed or failed</b><small>Final recorded outcome</small></li></ol></div></div></section>
<section class="section"><div class="container faq-layout"><div><div class="eyebrow">Common questions</div><h2>Know what to expect.</h2></div><div><?php foreach($page['faq'] as $faq):?><details><summary><?=e($faq[0])?></summary><p><?=e($faq[1])?></p></details><?php endforeach?></div></div></section>
<section class="section final-cta"><div class="container content-card"><div><div class="eyebrow">Your next step</div><h2>Manage requests from one secure workspace.</h2><p class="muted">Product eligibility and availability vary by account and jurisdiction.</p></div><div class="hero-actions"><a class="button button-primary" href="register.php">Get started</a><a class="button button-secondary" href="contact.php">Contact us</a></div></div></section>
<?php require __DIR__.'/public_footer.php';?>
