<?php
$pages = [
    'accounts' => ['Personal banking', 'A clear view of your everyday account.', 'See balances, activity, statements, and account details in one focused workspace.', ['Account visibility', 'Real activity, not sample chart data.', 'Clear records', 'Searchable transactions and consistent receipts.', 'USD foundation', 'The initial product experience is designed around US dollars.']],
    'cards' => ['Card center', 'Your cards, organized around control.', 'Manage safe card metadata and provider-backed verification without storing CVV or exposing full card numbers.', ['Masked by default', 'Only safe card identifiers belong in the interface.', 'Visa and Mastercard', 'Supported network functionality without endorsement claims.', 'Activity context', 'Connect card actions to traceable account records.']],
    'transfers' => ['Card-to-card transfers', 'Send with a clear confirmation trail.', 'Choose a source, select a beneficiary, review the amount and fee, then track the transfer through completion.', ['Review first', 'Confirm destination, amount, and applicable fee.', 'Step-up security', 'Sensitive transfers can require an additional verification step.', 'Traceable status', 'Receipts and status history keep activity understandable.']],
    'funding' => ['Visa and Mastercard funding', 'Fund through a provider-ready flow.', 'Valtoria is being structured for tokenized card funding. No live charge is represented until a real provider is configured.', ['Tokenized design', 'Raw card numbers and CVV are not part of the storage model.', 'Transparent totals', 'Amount, fee, and total are shown before confirmation.', 'Honest status', 'Sandbox activity is never presented as a real provider authorization.']],
    'credit' => ['Credit', 'Credit access for eligible Visa cardholders.', 'Eligibility is based on configured, explainable rules and review—not invented bureau data or guaranteed approval.', ['Eligibility clarity', 'See the factors required before applying.', 'Terms that match', 'Displayed amounts, rates, and schedules must match stored terms.', 'Application tracking', 'Follow review, decision, disbursement, and repayment status.']],
    'security' => ['Security', 'Practical controls for safer account access.', 'Valtoria uses layered session, verification, validation, and activity controls while clearly documenting remaining risks.', ['Protected sessions', 'Secure cookie settings and inactivity controls reduce session exposure.', 'Verification', 'Single-use, expiring codes protect sensitive journeys.', 'Activity awareness', 'Sign-in records make unusual access easier to identify.']],
    'help' => ['Help center', 'Straight answers when you need them.', 'Browse common guidance or contact support. Never share a password, one-time code, or complete card details with support.', ['Account access', 'Use password recovery if you cannot sign in.', 'Funding and transfers', 'Check status and reference details before contacting support.', 'Security concern', 'Change your password and report unrecognized activity promptly.']],
];
$page = $pages[$productPage] ?? null;
if (!$page) { http_response_code(404); exit('Page not found'); }
[$eyebrow, $heading, $intro, $features] = $page;
$pageTitle = $heading . ' | Valtoria Bank';
require __DIR__ . '/public_header.php';
?>
<section class="page-hero"><div class="container"><div class="eyebrow"><?= e($eyebrow) ?></div><h1><?= e($heading) ?></h1><p class="hero-copy"><?= e($intro) ?></p></div></section><section class="section"><div class="container grid-3"><?php for($i=0;$i<count($features);$i+=2): ?><article class="feature-card"><div class="feature-icon"><?= str_pad((string)(($i/2)+1),2,'0',STR_PAD_LEFT) ?></div><h3><?= e($features[$i]) ?></h3><p class="muted"><?= e($features[$i+1]) ?></p></article><?php endfor; ?></div></section><section class="section" style="background:#fff"><div class="container content-card"><h2>Ready to get started?</h2><p class="muted">Open an account or sign in to review the services currently available to you.</p><div class="hero-actions"><a class="button button-primary" href="register.php">Open an account</a><a class="button button-secondary" href="login.php">Sign in</a></div></div></section>
<?php require __DIR__ . '/public_footer.php'; ?>
