<?php
$appPage='cards'; $appTitle='Card center'; require __DIR__ . '/../includes/customer_header.php';
$service=new CardService($pdo); $error=''; $success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{requireCsrf(); $action=$_POST['action']??''; if($action==='add'){$service->addSandboxCard($customerId,$_POST['network']??'',$_POST['last_four']??'',$_POST['cardholder_name']??'',(int)($_POST['expiry_month']??0),(int)($_POST['expiry_year']??0));$success='Card metadata added and verified by the sandbox adapter. No card number or CVV was collected.';}elseif($action==='remove'){$service->remove($customerId,(int)($_POST['card_id']??0));$success='Card removed.';}}catch(Throwable $e){$error=$e->getMessage();}
}
$cards=$service->listForUser($customerId);
?>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif?>
<div class="notice">Sandbox card profiles store only a provider token, network, final four digits, cardholder label, and permitted expiry metadata. Never enter a full card number or CVV.</div>
<div class="app-grid"><section class="panel span-7"><h2>Linked cards</h2><?php if(!$cards):?><div class="empty">No cards linked yet.</div><?php else:?><div class="app-grid"><?php foreach($cards as $card):?><article class="card-tile span-6 <?=e($card['network'])?>"><div class="card-meta"><strong><?=e(ucfirst($card['network']))?></strong><span class="badge <?=e($card['verification_status'])?>"><?=e($card['verification_status'])?></span></div><div><div style="font-size:1.25rem;letter-spacing:.16em">•••• •••• •••• <?=e($card['last_four'])?></div><div class="card-meta"><span><?=e($card['cardholder_name'])?></span><span><?=str_pad((string)$card['expiry_month'],2,'0',STR_PAD_LEFT)?>/<?=e($card['expiry_year'])?></span></div></div><form method="post"><?=csrfField()?><input type="hidden" name="action" value="remove"><input type="hidden" name="card_id" value="<?=e($card['card_id'])?>"><button class="button button-secondary" type="submit">Remove</button></form></article><?php endforeach?></div><?php endif?></section><section class="panel span-5"><h2>Add sandbox card</h2><form method="post" class="form-grid"><?=csrfField()?><input type="hidden" name="action" value="add"><div class="field"><label for="network">Network</label><select id="network" name="network" required><option value="visa">Visa</option><option value="mastercard">Mastercard</option></select></div><div class="field"><label for="last_four">Last four digits</label><input id="last_four" name="last_four" inputmode="numeric" pattern="\d{4}" maxlength="4" required></div><div class="field full"><label for="cardholder_name">Cardholder name</label><input id="cardholder_name" name="cardholder_name" maxlength="100" required></div><div class="field"><label for="expiry_month">Expiry month</label><input id="expiry_month" name="expiry_month" type="number" min="1" max="12" required></div><div class="field"><label for="expiry_year">Expiry year</label><input id="expiry_year" name="expiry_year" type="number" min="<?=date('Y')?>" max="<?=date('Y')+20?>" required></div><div class="field full"><button class="button button-primary">Add card metadata</button></div></form></section></div>
<?php require __DIR__ . '/../includes/customer_footer.php'; ?>
