<?php
$appPage='cards'; $appTitle='Card center'; require __DIR__ . '/../includes/customer_header.php';
$service=new CardService($pdo); $error=''; $success='';
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{requireCsrf(); $action=$_POST['action']??''; if($action==='add'){$service->submitForReview($customerId,$_POST['network']??'',$_POST['last_four']??'',$_POST['cardholder_name']??'',(int)($_POST['expiry_month']??0),(int)($_POST['expiry_year']??0),$_POST['partner_reference']??'');$success='Card submitted. Operations will confirm compatibility before it can be used.';}elseif($action==='remove'){$service->remove($customerId,(int)($_POST['card_id']??0));$success='Card removed.';}}catch(Throwable $e){$error=$e->getMessage();}
}
$cards=$service->listForUser($customerId);
?>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?><?php if($success):?><div class="notice success"><?=e($success)?></div><?php endif?>
<div class="notice"><strong>Safe card review:</strong> enter the reference supplied by the partner card company and masked card details only. Never enter a full card number or security code. Operations will confirm compatibility before funding is enabled.</div>
<div class="app-grid"><section class="panel span-7"><span class="section-kicker">Your wallet</span><h2>Submitted cards</h2><?php if(!$cards):?><div class="empty"><strong>No cards submitted</strong><span>Add compatible partner-card metadata to begin review.</span></div><?php else:?><div class="app-grid"><?php foreach($cards as $card):?><article class="card-tile span-6 <?=e($card['network'])?>"><div class="card-meta"><strong><?=e(ucfirst($card['network']))?></strong><span class="badge <?=e($card['verification_status'])?>"><?=e($card['verification_status'])?></span></div><div><div class="masked-pan">•••• •••• •••• <?=e($card['last_four'])?></div><div class="card-meta"><span><?=e($card['cardholder_name'])?></span><span><?=str_pad((string)$card['expiry_month'],2,'0',STR_PAD_LEFT)?>/<?=e($card['expiry_year'])?></span></div></div><form method="post"><?=csrfField()?><input type="hidden" name="action" value="remove"><input type="hidden" name="card_id" value="<?=e($card['card_id'])?>"><button class="card-action" type="submit">Remove card</button></form></article><?php endforeach?></div><?php endif?></section><section class="panel span-5"><span class="section-kicker">Compatibility check</span><h2>Submit a card</h2><p class="panel-intro">Use the non-sensitive reference supplied by the partner. Approval is completed manually.</p><form method="post" class="form-grid"><?=csrfField()?><input type="hidden" name="action" value="add"><div class="field"><label for="network">Network</label><select id="network" name="network" required><option value="visa">Visa</option><option value="mastercard">Mastercard</option></select></div><div class="field"><label for="last_four">Last four digits</label><input id="last_four" name="last_four" inputmode="numeric" pattern="\d{4}" maxlength="4" autocomplete="off" required></div><div class="field full"><label for="partner_reference">Partner card reference <span>(optional)</span></label><input id="partner_reference" name="partner_reference" maxlength="80" autocomplete="off" placeholder="Reference from card partner"><small>Do not enter a card number or security code.</small></div><div class="field full"><label for="cardholder_name">Name on card</label><input id="cardholder_name" name="cardholder_name" maxlength="100" autocomplete="cc-name" required></div><div class="field"><label for="expiry_month">Expiry month</label><input id="expiry_month" name="expiry_month" type="number" min="1" max="12" required></div><div class="field"><label for="expiry_year">Expiry year</label><input id="expiry_year" name="expiry_year" type="number" min="<?=date('Y')?>" max="<?=date('Y')+20?>" required></div><div class="field full"><button class="button button-primary">Submit for review</button></div></form></section></div>
<?php require __DIR__ . '/../includes/customer_footer.php'; ?>
