<?php
$appPage='funding'; $appTitle='Card funding'; require __DIR__ . '/../includes/customer_header.php';
$fundingService=new FundingService($pdo,new SandboxCardFundingProvider()); $cards=(new CardService($pdo))->listForUser($customerId); $error=''; $result=null; $quote=null;
if($_SERVER['REQUEST_METHOD']==='POST'){
    try{requireCsrf();$action=$_POST['action']??'';
        if($action==='quote'){$amount=Money::fromDecimal($_POST['amount']??'');$quote=$fundingService->quote($amount);(new CardService($pdo))->ownedActiveCard($customerId,(int)$_POST['card_id']);$_SESSION['funding_quote']=$quote+['card_id'=>(int)$_POST['card_id'],'idempotency_key'=>bin2hex(random_bytes(24))];}
        elseif($action==='confirm'){if(empty($_SESSION['funding_quote']))throw new RuntimeException('Funding confirmation expired.');$pending=$_SESSION['funding_quote'];$result=$fundingService->fund($customerId,$pending['card_id'],$pending['amount_cents'],$pending['idempotency_key']);unset($_SESSION['funding_quote']);}
        elseif($action==='cancel'){unset($_SESSION['funding_quote']);}
    }catch(Throwable $e){$error=$e->getMessage();}
}
if(!$quote&&!empty($_SESSION['funding_quote']))$quote=$_SESSION['funding_quote'];
$history=$pdo->prepare('SELECT f.*,t.reference FROM card_fundings f JOIN financial_transactions t ON t.transaction_id=f.financial_transaction_id WHERE f.user_id=? ORDER BY f.initiated_at DESC LIMIT 10');$history->execute([$customerId]);
?>
<?php if($error):?><div class="notice error"><?=e($error)?></div><?php endif?><?php if($result):?><div class="notice success"><strong><?=e($result['reference'])?></strong> — <?=e($result['provider_message']??'Request accepted.')?></div><?php endif?>
<div class="notice">Provider mode: <strong>sandbox</strong>. Completing this flow changes the local sandbox ledger only; no external card is charged.</div>
<div class="app-grid"><section class="panel span-5"><h2><?= $quote?'Review funding':'Fund your account' ?></h2><?php if($quote):?><dl><dt>Amount credited</dt><dd class="money"><?=Money::format($quote['amount_cents'],true)?></dd><dt>Sandbox fee</dt><dd class="money"><?=Money::format($quote['fee_cents'],true)?></dd><dt>Total simulated charge</dt><dd class="money"><?=Money::format($quote['total_cents'],true)?></dd></dl><div class="actions"><form method="post"><?=csrfField()?><input type="hidden" name="action" value="confirm"><button class="button button-primary">Confirm sandbox funding</button></form><form method="post"><?=csrfField()?><input type="hidden" name="action" value="cancel"><button class="button button-secondary">Cancel</button></form></div><?php else:?><form method="post" class="form-grid"><?=csrfField()?><input type="hidden" name="action" value="quote"><div class="field full"><label for="card_id">Funding card</label><select id="card_id" name="card_id" required><option value="">Choose a verified card</option><?php foreach($cards as $card):?><option value="<?=e($card['card_id'])?>"><?=e(ucfirst($card['network']).' ending '.$card['last_four'])?></option><?php endforeach?></select><small><a href="card-center.php">Add a card</a> if none are available.</small></div><div class="field full"><label for="amount">Amount (USD)</label><input id="amount" name="amount" inputmode="decimal" placeholder="100.00" required></div><div class="field full"><button class="button button-primary">Review amount and fee</button></div></form><?php endif?></section><section class="panel span-7"><h2>Recent funding</h2><div class="table-wrap"><table class="data-table"><thead><tr><th>Reference</th><th>Network</th><th>Amount</th><th>Fee</th><th>Status</th><th>Date</th></tr></thead><tbody><?php foreach($history->fetchAll() as $row):?><tr><td><a href="transaction.php?reference=<?=urlencode($row['reference'])?>"><?=e($row['reference'])?></a></td><td><?=e(ucfirst($row['network']))?></td><td class="money"><?=Money::format((int)$row['amount_cents'])?></td><td><?=Money::format((int)$row['fee_cents'])?></td><td><span class="badge <?=e($row['status'])?>"><?=e($row['status'])?></span></td><td><?=e($row['initiated_at'])?></td></tr><?php endforeach?></tbody></table></div></section></div>
<?php require __DIR__ . '/../includes/customer_footer.php'; ?>
